name: Deploy to Azure

description: This GitHub Action deploys built artifacts to Azure.

runs:
  using: composite
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: build
        path: build
    - name: Connect to Azure
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5
      with:
        creds: ${{env.AZURE_CREDENTIALS}}
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@de617f46172a906d0617bb0e50d81e9e3aec24c8
      with:
        app-name: ${{env.AZURE_WEB_APP_NAME}}
        package: build
